version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: dynamic-profile-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - APP_ENV=production
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
